export type Salutation = 'Mr' | 'Ms' | 'Mrs' | 'Master' | 'Baby' | 'Baby of';
export type Sex = 'Male' | 'Female' | 'Other' | '';

export interface Patient {
  id?: number; // Unique patient ID for searching
  patient_code?: string; // Auto-generated patient code (e.g., P202511120001)
  salutation: Salutation;
  name: string;
  age_years: number;
  age_months: number;
  age_days: number;
  sex: Sex;
  guardian_name?: string;
  phone: string;
  address: string;
  email?: string;
  clinical_history?: string;
}

export interface Client {
    id: number;
    name: string;
    type: 'PATIENT' | 'REFERRAL_LAB' | 'INTERNAL';
    balance: number;
}

export interface Branch {
    id: number;
    name: string;
    address: string;
    phone?: string;
    email?: string;
    city?: string;
    state?: string;
    pincode?: string;
    isActive: boolean;
}

export interface TestTemplateParameter {
    name: string;
    type: 'number' | 'text' | 'heading'; // Added 'heading' type for section headers
    unit?: string;
    reference_range?: string;
    group?: string; // Optional group name for organizing parameters
}

export interface TestTemplate {
  id: number;
  code: string;
  name: string;
  category: string;
  price: number;
  b2b_price: number;
  isActive: boolean;
  parameters: {
    fields: TestTemplateParameter[];
  };
  reportType: 'standard' | 'culture';
  defaultAntibioticIds?: number[];
  sampleType?: string;
  tatHours?: number; // Turnaround time in hours
}

export type VisitTestStatus = 'PENDING' | 'SAMPLE_COLLECTED' | 'REJECTED' | 'IN_PROGRESS' | 'AWAITING_APPROVAL' | 'APPROVED' | 'PRINTED' | 'COMPLETED';

// --- NEW TYPES FOR CULTURE REPORT ---
export interface Antibiotic {
  id: number;
  name: string;
  abbreviation: string;
  isActive: boolean;
}

export interface SensitivityResult {
  antibioticId: number;
  sensitivity: 'S' | 'R' | 'I'; // Sensitive, Resistant, Intermediate
}

export interface CultureResult {
  growthStatus: 'growth' | 'no_growth';
  organismIsolated?: string;
  colonyCount?: string;
  sensitivity?: SensitivityResult[];
  remarks?: string;
}
// --- END NEW TYPES ---


export interface VisitTest {
  id: number; // Unique ID for this specific test instance in a visit
  visitId: number;
  patientName: string; // Denormalized for easier display
  visitCode: string; // Denormalized for easier display
  referredDoctorName?: string; // Referring doctor name
  referredDoctorDesignation?: string; // Referring doctor designation
  otherRefDoctor?: string; // Other referring doctor (free text)
  template: TestTemplate;
  status: VisitTestStatus;
  collectedBy?: string;
  collectedAt?: string; // ISO String
  specimen_type?: string;
  results?: Record<string, string | number>;
  cultureResult?: CultureResult; // New field for structured culture results
  enteredBy?: string; // Lab technician who entered the results
  enteredAt?: string; // ISO String - when results were entered
  approvedBy?: string;
  approvedAt?: string; // ISO String
  rejection_count?: number;
  last_rejection_at?: string;
  created_at?: string; // ISO String - when the test was created
}


export interface B2BClientInfo {
  id: number;
  name: string;
  type: 'PATIENT' | 'REFERRAL_LAB' | 'INTERNAL';
  balance: number;
}

export interface Visit {
  id: number;
  patient: Patient;
  referred_doctor_id?: number;
  referred_doctor_name?: string;
  referred_doctor_designation?: string;
  ref_customer_id?: number;
  other_ref_doctor?: string;
  other_ref_customer?: string;
  registration_datetime?: string; // YYYY-MM-DD HH:MM
  visit_code: string;
  created_at: string; // ISO String
  total_cost: number;
  amount_paid: number;
  payment_mode?: 'Cash' | 'Card' | 'UPI' | '';
  due_amount: number;
  tests: number[]; // Array of VisitTest IDs
  b2bClient?: B2BClientInfo | null; // B2B client information if visit is from a B2B client
  qr_code?: string; // Base64 data URL of QR code generated by backend
  verification_url?: string; // URL for verifying the report
}

export interface Signatory {
  id: number;
  name: string;
  title: string;
}

export interface Approver {
  id: number;
  user_id?: number;
  name: string;
  title: string;
  role: string;
  display_order: number;
  show_on_print: boolean;
  signature_image_url?: string;
  is_active: boolean;
}

export interface ClientPrice {
    clientId: number;
    testTemplateId: number;
    price: number;
}

export interface LedgerEntry {
    id: number;
    clientId: number;
    visitId?: number;
    type: 'DEBIT' | 'CREDIT';
    amount: number;
    description: string;
    created_at: string; // ISO String
}

export interface AuditLog {
    id: number;
    timestamp: string; // ISO String
    username: string;
    action: string;
    details: string;
    user_id?: number;
    resource?: string;
    resource_id?: number;
    ip_address?: string;
    old_values?: any;
    new_values?: any;
    user_role?: string;
}

export interface PatientEditRequest {
    id: number;
    patient_id: number;
    requested_by_user_id: number;
    requested_by_username: string;
    request_type: 'NAME_CHANGE' | 'CRITICAL_INFO_CHANGE' | 'GENERAL_EDIT';
    old_values: any;
    new_values: any;
    reason?: string;
    status: 'PENDING' | 'APPROVED' | 'REJECTED';
    reviewed_by_user_id?: number;
    reviewed_by_username?: string;
    review_comment?: string;
    reviewed_at?: string;
    created_at: string;
    updated_at: string;
    patient_name?: string;
    patient_phone?: string;
}

export interface ResultRejection {
    id: number;
    visit_test_id: number;
    rejected_by_user_id: number;
    rejected_by_username: string;
    rejection_reason: string;
    old_results?: any;
    status: 'PENDING_CORRECTION' | 'CORRECTED' | 'RESOLVED';
    resolved_by_user_id?: number;
    resolved_by_username?: string;
    resolved_at?: string;
    created_at: string;
    updated_at: string;
    visit_id?: number;
    test_template_id?: number;
    test_status?: string;
    test_name?: string;
    test_code?: string;
    visit_code?: string;
    patient_name?: string;
}


export type Role = 'SUDO' | 'ADMIN' | 'RECEPTION' | 'PHLEBOTOMY' | 'LAB' | 'APPROVER';

export type Permission =
    | 'VIEW_RECEPTION'
    | 'CREATE_VISIT'
    | 'COLLECT_DUE_PAYMENT'
    | 'VIEW_PHLEBOTOMY'
    | 'COLLECT_SAMPLE'
    | 'VIEW_LAB'
    | 'ENTER_RESULTS'
    | 'VIEW_APPROVER'
    | 'APPROVE_RESULTS'
    | 'VIEW_ADMIN_PANEL'
    | 'MANAGE_USERS'        // SUDO Only
    | 'MANAGE_ROLES'        // SUDO Only
    | 'MANAGE_TESTS'
    | 'MANAGE_PRICES'
    | 'MANAGE_B2B'
    | 'MANAGE_ANTIBIOTICS'  // ADMIN/SUDO
    | 'EDIT_APPROVED_REPORT' // SUDO Only
    | 'VIEW_AUDIT_LOG'      // SUDO Only
    | 'VIEW_B2B_DASHBOARD';  // B2B Client Only

export type RolePermissions = Record<Role, Permission[]>;

export interface User {
  id: number;
  username: string;
  role: Role;
  isActive: boolean;
  permissions: Permission[];
  signatureImageUrl?: string;
}

export type UserWithPassword = User & { password_hash: string };

export interface Unit {
  id: number;
  name: string;
  symbol: string;
  category?: string;
  description?: string;
  isActive: boolean;
}